### ISSUE TITLE
Add contracts endpoint by address

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-decoder-service#12]
# What is needed?
Implement the contracts endpoint by id following the same structure than https://safe-transaction-mainnet.safe.global/#/contracts/contracts_retrieve with multichain support.

# Proposal multichain support
I would like to add the multichain support by default for this and other endpoints and filter by query param the chain that the client wants. 
For example:
`GET contracts/{address}/?chain_id=chain_id
`If chain_id is not used to filter the endpoint should return all the contract and abis for all the chains where the contract is supported. 
If chain_id is used to filter just return the corresponding chain
Even we could think about add the chain_id as an array parameter to get a group of chains.  

# Tasks
- [x] Add the necessary models (chains, Contracts, Abis... )
- [x] Add the endpoint contract by address
- [x] Add test for the implemented endpoint
